local utils = require'shins.utils'

local setup_mappings = function()
    -- We don't want arrow keys
    utils.key_mapper('n', '<up>',       '<nop>')
    utils.key_mapper('n', '<down>',     '<nop>')
    utils.key_mapper('n', '<left>',     '<nop>')
    utils.key_mapper('n', '<right>',    '<nop>')
    utils.key_mapper('i', '<up>',       '<nop>')
    utils.key_mapper('i', '<down>',     '<nop>')
    utils.key_mapper('i', '<left>',     '<nop>')
    utils.key_mapper('i', '<right>',    '<nop>')

    utils.key_mapper('i', '<S-Tab>',    'v:lua.s_tab_complete()', { expr = true })
    utils.key_mapper('s', '<S-Tab>',    'v:lua.s_tab_complete()', { expr = true })
    utils.key_mapper('i', '<C-Space>',  'compe#complete()', { expr = true })
    utils.key_mapper('i', '<C-y>',      'compe#confirm("<CR>")', { expr = true })
    utils.key_mapper('i', '<C-e>',      'compe#close("<C-e>")', { expr = true })
    utils.key_mapper('i', '<C-f>',      'compe#scroll({ "delta": +4 })', { expr = true })
    utils.key_mapper('i', '<C-d>',      'compe#scroll({ "delta": -4 })', { expr = true })
    utils.key_mapper('n', 'gd',         '<cmd>lua vim.lsp.buf.definition()<CR>')
    utils.key_mapper('n', 'gD',         '<cmd>lua vim.lsp.buf.declaration()<CR>')
    utils.key_mapper('n', 'gi',         '<cmd>lua vim.lsp.buf.implementation()<CR>')
    utils.key_mapper('n', 'gw',         '<cmd>lua vim.lsp.buf.document_symbol()<CR>')
    utils.key_mapper('n', 'gW',         '<cmd>lua vim.lsp.buf.workspace_symbol()<CR>')
    utils.key_mapper('n', 'gr',         '<cmd>lua vim.lsp.buf.references()<CR>')
    utils.key_mapper('n', 'gt',         '<cmd>lua vim.lsp.buf.type_definition()<CR>')
    utils.key_mapper('n', '<c-k>',      '<cmd>lua vim.lsp.buf.signature_help()<CR>')
    utils.key_mapper('n', '<leader>af', '<cmd>lua vim.lsp.buf.code_action()<CR>')
    utils.key_mapper('n', '<leader>rn', '<cmd>lua vim.lsp.buf.rename()<CR>')
    utils.key_mapper('n', '<leader>p',  '<cmd>lua vim.lsp.buf.formatting()<CR>')
    utils.key_mapper('n', '<leader>ff',  '<cmd>lua require"telescope.builtin".find_files({hidden = true})<CR>')
    utils.key_mapper('n', '<leader>fg',  '<cmd>lua require"telescope.builtin".live_grep()<CR>')
    utils.key_mapper('n', '<leader>fh', '<cmd>lua require"telescope.builtin".help_tags()<CR>')
    utils.key_mapper('n', '<leader>fb', '<cmd>lua require"telescope.builtin".buffers()<CR>')
    utils.key_mapper('n', '<leader>z',  '<cmd>luafile $MYVIMRC<CR>')
    utils.key_mapper('n', '<leader>t',  '<cmd>NERDTreeFind<CR>')
    utils.key_mapper('n', '<leader>tt', '<cmd>NERDTreeToggle<CR>')
    utils.key_mapper('n', '<leader>tc', '<cmd>NERDTreeClose<CR>')
    utils.key_mapper('n', '<leader>tf', '<cmd>NERDTreeFocus<CR>')
    utils.key_mapper('n', '<leader>g',  '<cmd>Gstatus<CR>')
    utils.key_mapper('n', '<leader>x',  '<cmd>bd<CR>')
    utils.key_mapper('n', '<leader>xx', '<cmd>%bd<CR>')
    utils.key_mapper('n', '<C-c>',      '<cmd>bp|bd #<CR>')
    utils.key_mapper('n', '<leader>r',  '<cmd>%s/<<C-r><C-w>>/')
    utils.key_mapper('n', '<leader>u',  '<cmd>UndotreeToggle<CR>')
    utils.key_mapper('n', '<leader>u',  '<cmd>UndotreeToggle<CR>')
    utils.key_mapper('n', '<leader>j',  '<C-w><C-j>')
    utils.key_mapper('n', '<leader>k',  '<C-w><C-k>')
    utils.key_mapper('n', '<leader>l',  '<C-w><C-l>')
    utils.key_mapper('n', '<leader>h',  '<C-w><C-h>')
    utils.key_mapper('n', '<esc>',      '<cmd>noh<return><esc>')
    utils.key_mapper('n', '<leader>lo', ':lopen<CR>')
    utils.key_mapper('n', '<leader>p', ':PrettierAsync<CR>')
end

setup_mappings()
